### ISSUE TITLE
Touching the UI under the tip

### ISSUE THREAD

**Issue by Rob117** [frichti/react-native-tips#11]
First, awesome library. Starred!

So, you can wrap children in tips to have the child display while the rest of the screen is blanked out. Would it be possible to, for example, make it so that the tip won't progress/trigger the close function unless you tap inside the highlighted child's area? Maybe using touchable highlight or something?

I would have no problem writing in custom code to make it happen, I'm just not sure where to even start. For example, even something like

`<Tip selectableField=[-30,-10-10,10]>`

to create a touchable field relative to the tip box.

Clearly, being able to click the area representing the child component underneath would be the best (or the component itself if it is a button / touchable highlight), but I'm really open to any suggestion to add this functionality.

**Comment by myvertigo** [comment]
Hello @Rob117  and thank you for your support :)

I think the best way would be to add a property to activate/deactivate the close function when touching the highlighted element.

Would this feature will resolve your request ?

**Comment by Rob117** [comment]
Absolutely! Essentially, touch element -> Callback would be excellent for me! This helps the user touch inside of a specific area.

**Comment by myvertigo** [comment]
This feature is now available in v0.0.10: just set enableChildrenInteraction to true in your Tips component to enable interaction without closing the Tooltips.

**Comment by Rob117** [comment]
So happy, will test!
