### ISSUE TITLE
Node of type rule not supported as an inline style

### ISSUE THREAD

**Issue by Joshuabaker2** [frichti/react-native-tips#12]
I am getting the error "Node of type rule not supported as an inline style" when running my project on an Android device, which I traced back to coming from this module. 

Unfortunately the error was not any more specific than this, but I hunted it down and it seemed to stem from the "shadow-offset" style. Removing this caused the error to go away (and allowed react-native-tips to work properly in Android). 

I've made a fork with this change, so PR incoming!

**Comment by Joshuabaker2** [comment]
Pull request #13 addresses these changes.

**Comment by myvertigo** [comment]
Hi @Joshuabaker2 and thank you for supporting this package.
I had already noticed that the property "shadow" sometimes generate warnings or errors. I especially tested on iPhone but it is possible that the behavior is different on Android.
Thank you for the PR, it will be validated for the next update 😀👍
